export const items = [
  {
    id: 1,
    name: "Akinrotimi Akindele",
    invoice: "12mn3",
    receipt: "09vnb",
    date: "12-03-22",
    pin: "",
  },
  {
    id: 2,
    name: "Esho Oluwasegun",
    invoice: "12mn3",
    receipt: "09vnb",
    date: "12-03-22",
    pin: "",
  },
  {
    id: 3,
    name: "Awosika Ibukun",
    invoice: "12mn3",
    receipt: "09vnb",
    date: "12-03-22",
    pin: "",
  },
  {
    id: 4,
    name: "Ayeni Bukunmi",
    invoice: "13mn3",
    receipt: "08vnb",
    date: "12-03-22",
    pin: "",
  },
  {
    id: 5,
    name: "Aromodele Timileyin",
    invoice: "13mn3",
    receipt: "08vnb",
    date: "12-03-22",
    pin: "",
  },
  {
    id: 6,
    name: "Esho Adetunji",
    invoice: "12mn3",
    receipt: "09vnb",
    date: "12-03-22",
    pin: "",
  },
  {
    id: 7,
    name: "Akojede Peter",
    invoice: "12mn3",
    receipt: "09vnb",
    date: "12-03-22",
    pin: "",
  },
  {
    id: 8,
    name: "Olaoye Femi",
    invoice: "12mn3",
    receipt: "09vnb",
    date: "12-03-22",
    pin: "",
  },
  {
    id: 9,
    name: "Olmailekan Francis",
    invoice: "12mn3",
    receipt: "09vnb",
    date: "12-03-22",
    pin: "",
  },
  {
    id: 10,
    name: "Ezegwu Francis",
    invoice: "12mn3",
    receipt: "09vnb",
    date: "12-03-22",
    pin: "",
  },
  {
    id: 11,
    name: "Adejayan Mary",
    invoice: "12mn3",
    receipt: "09vnb",
    date: "12-03-22",
    pin: "",
  },
];
